# Generated by Django 3.1 on 2020-09-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0034_auto_20200827_1529'),
        ('board', '0006_auto_20200916_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='houses.house'),
        ),
    ]
