# Generated by Django 3.1 on 2020-09-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_reservation_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationday',
            old_name='room_id',
            new_name='room',
        ),
    ]
