# Generated by Django 3.1 on 2020-09-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20200923_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('MAINTENANCE', 'Maintenance'), ('FAST_CLOSE', 'Fast close'), ('TMP_CLOSE', 'Temporary close')], max_length=25, null=True),
        ),
    ]
