# Generated by Django 3.1.1 on 2020-09-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20200925_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_contact_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_contact_ids',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
