# Generated by Django 3.1.2 on 2020-10-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20200930_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationroom',
            name='rate_plan_id_original',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
