# Generated by Django 3.1.2 on 2020-10-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_auto_20201019_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='opportunity_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='quotation_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_contact_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
