# Generated by Django 3.1.2 on 2020-11-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_auto_20201022_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationroom',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationroom',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
